### ISSUE TITLE
关于云盘仓库的隐私问题

### ISSUE THREAD

**Issue by G1t-hub** [TheBloodthirster/BUAA_Course_Sharing#2]
云盘仓库应该设置成内部共享，HTTP共享公网仍可自由下载。
![image](https://user-images.githubusercontent.com/56796909/101309680-e5148600-3887-11eb-9e0f-eeb152563367.png)

**Comment by TheBloodthirster** [comment]
已经取消http共享 的下载权限，可以通过内部共享连接下载，或者保存文件夹到自己网盘

AnyShare://Iaoceot/资料统计
