### ISSUE TITLE
链接地址失效

### ISSUE THREAD

**Issue by JamiePW** [TheBloodthirster/BUAA_Course_Sharing#30]
[https://bhpan.buaa.edu.cn:443/link/6C14718EE66E6F25956D54E1BECC185A](https://bhpan.buaa.edu.cn/link/6C14718EE66E6F25956D54E1BECC185A)

**Comment by TheBloodthirster** [comment]
估计是毕业学校把我云盘的账号清空了，看看有没有同学有保存的重新发一份出来
