### ISSUE TITLE
2024.11.30 链接地址依旧失效

### ISSUE THREAD

**Issue by YJ8672** [TheBloodthirster/BUAA_Course_Sharing#34]

**Comment by TheBloodthirster** [comment]
[https://bhpan.buaa.edu.cn/link/AA8B9E9C67DA0F40B4BB528914967E83CF](https://bhpan.buaa.edu.cn/link/AA8B9E9C67DA0F40B4BB528914967E83CF%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9Ao3PL)

提取码：o3--删除防爬4个字母--PL
